"""
Platinum Tier - Health Monitoring Script
Monitors cloud agent and restarts if crashed
"""
import os
import time
import subprocess
import psutil
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path
from datetime import datetime

class HealthMonitor:
    def __init__(self, vault_path):
        self.vault = Path(vault_path)
        self.cloud_process = None
        self.monitoring = True
        
    def check_cloud_agent_status(self):
        """Check if cloud agent is running"""
        try:
            # Look for the cloud orchestrator process
            for proc in psutil.process_iter(['pid', 'name', 'cmdline']):
                if 'cloud_orchestrator.py' in ' '.join(proc.info['cmdline']) or 'python' in proc.info['name'] and 'cloud_orchestrator' in ' '.join(proc.info['cmdline']):
                    return True, proc.info['pid']
            return False, None
        except Exception as e:
            print(f"[HEALTH] Error checking process: {e}")
            return False, None
    
    def start_cloud_agent(self):
        """Start the cloud agent if it's not running"""
        try:
            print("[HEALTH] Starting Cloud Agent...")
            self.cloud_process = subprocess.Popen(['python', 'cloud_orchestrator.py'])
            print(f"[HEALTH] Cloud Agent started with PID: {self.cloud_process.pid}")
            
            # Log the restart
            log_file = self.vault / 'Logs' / 'health_monitor.log'
            timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            with open(log_file, 'a') as f:
                f.write(f"[{timestamp}] HEALTH_MONITOR: Cloud Agent started with PID {self.cloud_process.pid}\n")
            
            return True
        except Exception as e:
            print(f"[HEALTH] Failed to start Cloud Agent: {e}")
            self.send_alert(f"Failed to start Cloud Agent: {e}")
            return False
    
    def send_alert(self, message):
        """Send alert via email or create alert file"""
        # For now, create an alert file in the vault
        alerts_dir = self.vault / 'Alerts'
        alerts_dir.mkdir(exist_ok=True)
        
        alert_file = alerts_dir / f'alert_{int(datetime.now().timestamp())}.md'
        alert_content = f"""---
type: system_alert
timestamp: {datetime.now().isoformat()}
severity: high
---

# System Alert

## Message
{message}

## Action Taken
Health monitor attempted recovery

## Status
Monitoring continues

---
*Alert generated by Health Monitor*
"""
        alert_file.write_text(alert_content)
        print(f"[HEALTH] Alert created: {alert_file.name}")
        
        # In a real implementation, this would send an email
        # using the configured email settings
    
    def log_status(self, status):
        """Log health status"""
        log_file = self.vault / 'Logs' / 'health_monitor.log'
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        with open(log_file, 'a') as f:
            f.write(f"[{timestamp}] HEALTH_STATUS: {status}\n")
    
    def run(self):
        """Main monitoring loop"""
        print("[HEALTH] Starting Health Monitor for Cloud Agent")
        print("[HEALTH] Monitoring Cloud Agent 24/7")
        print("=" * 50)
        
        # Initial check
        is_running, pid = self.check_cloud_agent_status()
        if not is_running:
            print("[HEALTH] Cloud Agent not running, starting it...")
            self.start_cloud_agent()
        else:
            print(f"[HEALTH] Cloud Agent is running with PID: {pid}")
        
        try:
            while self.monitoring:
                # Check cloud agent status
                is_running, pid = self.check_cloud_agent_status()
                
                if not is_running:
                    print(f"[HEALTH] Cloud Agent is DOWN at {datetime.now()}")
                    self.log_status("Cloud Agent DOWN - Attempting restart")
                    
                    # Attempt to restart
                    success = self.start_cloud_agent()
                    if success:
                        print(f"[HEALTH] Cloud Agent restarted successfully")
                        self.log_status("Cloud Agent RESTARTED")
                        self.send_alert("Cloud Agent was down and has been restarted")
                    else:
                        print(f"[HEALTH] Failed to restart Cloud Agent")
                        self.log_status("Cloud Agent FAILED to restart")
                        self.send_alert("Cloud Agent is down and could not be restarted")
                else:
                    print(f"[HEALTH] Cloud Agent OK with PID {pid}")
                    self.log_status(f"Cloud Agent OK with PID {pid}")
                
                # Wait before next check (every 5 minutes)
                time.sleep(300)  # 5 minutes
                
        except KeyboardInterrupt:
            print("\n[HEALTH] Health Monitor stopped by user")
            self.monitoring = False
        except Exception as e:
            print(f"[HEALTH] Error in Health Monitor: {e}")
            self.send_alert(f"Health Monitor error: {e}")

if __name__ == "__main__":
    VAULT_PATH = "C:/Users/manal/OneDrive/Desktop/Hacakthon 0/AI_Employee_Vault_Platinum"
    monitor = HealthMonitor(VAULT_PATH)
    monitor.run()